@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

' LAYOUT_WITH_LEGEND()

title Архитектура 1С:Учет ГСМ

Person(Бухгалтер,   Бухгалтер,  "Специалист по учету ГСМ")
Person(Нарядчик,   Нарядчик,  "Диспетчер автомобильного транспорта")

' Системы
System_Boundary(УчетГСМ, "1C:Учет ГСМ") {
     Container(Запасы, "Запасы",, "")
     Container(Расчеты, "Расчеты с сотрудниками",, "")
 }

System_Boundary(Бухгалтерия, "1C:Бухгалтерия") {
     Container(ЗапасыБух, "Запасы", "")
}


System_Ext(RMQ, "Rabbit MQ")  

' Связи
Rel(Нарядчик, Запасы,   "Ввод путевых листов")
Rel(Бухгалтер, Запасы,  "Ввод данных по поступлению ГСМ")
Rel(Бухгалтер, Расчеты, "Ввод данных по взаиморасчетам")

' новые связи
Rel(Запасы, RMQ, "Путевой лист", "AMQ")
Rel(RMQ, ЗапасыБух, "Путевой лист", "AMQ")

' Расположение
Lay_U(Запасы, УчетГСМ)

@enduml
